#!/bin/sh

set -e
set -x

if command -v valgrind; then
    VALGRIND="valgrind --error-exitcode=1"
fi

echo 'libgssapi.so.3 mechglue_internal_krb5_init' > my_gssapi_mech.conf

GSSAPI_MECH_CONF=my_gssapi_mech.conf \
		GSASL="$VALGRIND /usr/bin/gsasl" \
		debian/tests/gsasl-dovecot-gssapi.sh

exit 0
