#!/bin/sh

set -e

WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM

pkg-config --cflags libgssglue
pkg-config --cflags libgssglue | grep '^-I/usr/include/gssglue'
echo PASS: pkg-config --cflags libgssglue

pkg-config --libs libgssglue
pkg-config --libs libgssglue | grep '^-lgssglue -ldl'
echo PASS: pkg-config --libs libgssglue

for f in $(ls tests/*.c); do
    echo $f
    gcc -I$WORKDIR -o $WORKDIR/foo $f `pkg-config --cflags --libs libgssglue` 2>/dev/null
    echo PASS: gcc $f
    $WORKDIR/foo
    echo PASS: $f
done

exit 0
